version: "3.8"

volumes:
  dbvolume:

services:
  db:
    build: ./database
    restart: unless-stopped
    container_name: database
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - dbvolume:/var/lib/mysql
  backend:
    depends_on:
      - db
    build: ./backend
    restart: unless-stopped
    container_name: backend
    env_file: ./.env
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    stdin_open: true